version: '3.8'

services:
  frontend:
    build: .
    ports:
      - "80:80"
      - "443:443"
    environment:
      - NODE_ENV=production
    depends_on:
      - backend
    networks:
      - app-network
    restart: unless-stopped

  backend:
    build: ./server
    ports:
      - "8787:8787"
    environment:
      - NODE_ENV=production
      - PORT=8787
    networks:
      - app-network
    restart: unless-stopped

networks:
  app-network:
    driver: bridge

volumes:
  # Add any persistent volumes if needed
  # - ./data:/app/data
