global:
  scrape_interval: 15s
  evaluation_interval: 15s

rule_files:
  # - "first_rules.yml"
  # - "second_rules.yml"

scrape_configs:
  # Prometheus itself
  - job_name: 'prometheus'
    static_configs:
      - targets: ['localhost:9090']

  # Ever Life Vault Backend
  - job_name: 'ever-life-vault-backend'
    static_configs:
      - targets: ['backend:8787']
    metrics_path: '/metrics'
    scrape_interval: 10s
    scrape_timeout: 5s

  # Ever Life Vault Web (nginx)
  - job_name: 'ever-life-vault-web'
    static_configs:
      - targets: ['web:80']
    metrics_path: '/nginx_status'
    scrape_interval: 10s
    scrape_timeout: 5s

  # Docker containers
  - job_name: 'docker'
    static_configs:
      - targets: ['localhost:9323']
    scrape_interval: 15s

  # Node Exporter (if available)
  - job_name: 'node-exporter'
    static_configs:
      - targets: ['localhost:9100']
    scrape_interval: 15s

  # cAdvisor (if available)
  - job_name: 'cadvisor'
    static_configs:
      - targets: ['localhost:8080']
    scrape_interval: 15s
