// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://ldnilzmkufdosagwowgd.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6Imxkbmlsem1rdWZkb3NhZ3dvd2dkIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTQxNDAxNTMsImV4cCI6MjA2OTcxNjE1M30.Ss9QWHypQcrAlz0FSWGBVPvriTMJCcfS2ok_cMuvT5M";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: sessionStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});